003 view capability
craigd2387/moves-like-swagger-ui pull request #12
Opened 2023-11-16 13:16 UTC by craigd2387

2023-11-16 13:27 UTC, eoinmcbennett commented on views/list-job-roles.html
>              <tr class="job-role-row">
Would the row itself not benefit from an id?

2023-11-16 13:27 UTC, eoinmcbennett approved these changes

2023-11-16 14:04 UTC, shaunganley requested changes

2023-11-16 14:04 UTC, shaunganley commented on package.json
> +    "ui-test": "npm start > /dev/null 2>&1 & sleep 10 && ts-mocha -p ./tsconfig.json test/unit/service/ui/login-page.test.ts --timeout 10000",
this looks like it will only test the login page?

2023-11-17 09:25 UTC, chrisknos approved these changes

2023-11-17 11:39 UTC, shaunganley approved these changes

2023-11-17 14:45 UTC, merged