026 add branding to the product
craigd2387/moves-like-swagger-ui pull request #8
Opened 2023-11-14 11:40 UTC by craigd2387

2023-11-14 11:56 UTC, eoinmcbennett approved these changes

2023-11-14 14:32 UTC, shaunganley requested changes

2023-11-14 14:32 UTC, shaunganley commented on views/index.html
> +    <header id="header" class="header">
could you move the header and footer and any imports to a master template file that can be extended by this file and any subsequent ones without having to copy/paste all this code

2023-11-15 11:27 UTC, shaunganley approved these changes

2023-11-15 13:45 UTC, shaunganley approved these changes

2023-11-15 14:34 UTC, merged